import type { EvalSource } from '../types';

interface Props {
  source: EvalSource;
  label: string;
}

export default function SourceBadge({ source, label }: Props) {
  const isGemini = source === 'gemini';
  const dot = isGemini ? 'text-ember' : 'text-term-warn';
  const fg = isGemini ? 'text-fg-dim' : 'text-term-warn';
  const tag = isGemini ? 'gemini' : 'heuristic · offline';
  const hint = isGemini
    ? 'generated by the llm judge'
    : 'gemini was unavailable — compiled deterministically';

  return (
    <div className="flex items-center gap-2 text-xs tabular text-fg-mute px-1">
      <span className={dot}>●</span>
      <span className="text-fg-faint">[{label}]</span>
      <span className={fg}>{tag}</span>
      <span className="text-fg-faint">·</span>
      <span className="text-fg-mute hidden sm:inline">{hint}</span>
    </div>
  );
}
